### PR TITLE
Change the bulk require to use Webpack's request.context

### LINKED ISSUE #44: doesn't work with webpack

### PR DESCRIPTION
**Pull request by salockhart**
From what I can tell, this module doesn't work in Webpack because of the bulk-require module, and can be fixed by using Webpack's `require.context`.

This might break the module for Browserify, however - I've not had a chance to test.  It might be better as a fork in that case.

Fixes #44

### CODE REVIEW

**Comment by BrandonCopley** [comment]
I would rather not break browserify. If we can test and ensure browserify is working I can merge this in.

**Comment by salockhart** [comment]
Completely agree.  If I have a chance I can test it - I've not used it with Browserify.

**Comment by debbiepeng** [comment]
It would be really helpful if this was checked in. Thanks!

**Comment by BrandonCopley** [comment]
If someone can test this and get the CI to build I can merge it.

**Pull request closed without merging**
